TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Jonnitto.MultiColumn': true

    userInterface:
      translation:
        autoInclude:
          'Jonnitto.MultiColumn': ['NodeTypes/*']

Jonnitto:
  MultiColumn:
    rowClass: row
    Media:
      defaultMode: height # height or width 
      baseWith: 2560
      class:
        containerFluid: false
        row: jonnitto-multicolumn-media--row
